name: Build App

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'default.nix'
      - 'flake.lock'
      - 'flake.nix'
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  nix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v31

      - name: Build App
        run: nix build .#default

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm]

    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update System
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Setup Python
        uses: actions/setup-python@v5
        if: matrix.os == 'macos-latest'
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install flatpak dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install flatpak flatpak-builder elfutils -y
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/19.08 org.electronjs.Electron2.BaseApp/x86_64/stable -y

      - name: Install Packages
        run: pnpm i

      - name: Publish App
        if: github.ref == 'refs/heads/main'
        run: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build App
        if: github.ref == 'refs/heads/dev'
        run: pnpm run make

      - name: Rename Artifacts
        if: github.ref == 'refs/heads/dev'
        shell: bash
        run: |
          find out/make -type f -name "*:*" | while read file; do
            newname=$(echo "$file" | tr ':' '-')
            mv "$file" "$newname"
          done

      - name: Upload Artifacts
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: out/make/**/*
          if-no-files-found: warn
