name: Build App

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'flake.lock'
      - 'flake.nix'
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    permissions: write-all

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Update System
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Setup Python
        uses: actions/setup-python@v5
        if: matrix.os == 'macos-latest'
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install flatpak dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install flatpak flatpak-builder elfutils -y
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/19.08 org.electronjs.Electron2.BaseApp/x86_64/stable -y

      - name: Install Packages
        run: pnpm i

      - name: Publish App
        run: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
