name: Build App

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    permissions: write-all

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        if: matrix.os == 'macos-latest'
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install flatpak-builder elfutils -y

      - name: Install Packages
        run: npm i

      - name: Publish App
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
